---
title: Using H2S  produced by Saccharomyces cerevisiae for the removal of copper from
  wastewater
author: "Criado Iwamoto Lemaire"
date: "2023-05-30"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loaddata, echo=FALSE, results="hide"}
library(tidyverse)
library(cowplot)
library(sf)
library(gstat)
library(spdep)
library(sp)
library(gridExtra)
library(GGally)
library(mapview)
library(RColorBrewer)
library(spatialreg)
library(agridat)
library(nlme)
library(sp)

mydata <- read.table('Table.csv', header = TRUE, sep = ",")


```

```{r colums}
colnames(mydata)
names(mydata)[names(mydata) == "X.Cu..initiale..mg.l."] <- "Initial_Cu_mg/l"
names(mydata)[names(mydata) == "final..Cu.mg.l"] <- "Final_Cu_mg/l"
names(mydata)[names(mydata) == "decrease..mg.l."] <- "Decrease_Cu.mg.l"
names(mydata)[names(mydata) == "X.decrease"] <- "%_decrease"
mydata
```

```{r summary}
summary(mydata)
```

```{r plot}

```
